name: Deploy https://hangtiancheng.github.io/h homepage

on:
  push:
    branches: [main]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: pages
  cancel-in-progress: false

jobs:
  build:
    if: "${{ github.event_name == 'workflow_dispatch' || github.event.head_commit.message == 'ci: Deploy homepage' }}"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0
      - name: Setup pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 10.33.0
      - name: Setup node
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm
      - name: Setup pages
        uses: actions/configure-pages@v4
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Build with vitepress
        run: pnpm build
      - name: Build with swifty-docs
        run: pnpm build:swifty
        env:
          DOCS_PASSWORD: ${{ secrets.DOCS_PASSWORD }}
      - name: Build with lark-docs
        run: pnpm build:lark
        env:
          DOCS_PASSWORD: ${{ secrets.DOCS_PASSWORD }}
      - name: Merge swifty-docs site into /h/swifty-docs/
        run: |
          mkdir -p ./.vitepress/dist/swifty-docs
          cp -r ./dist-swifty/* ./.vitepress/dist/swifty-docs/
      - name: Merge lark-docs site into /h/lark-docs/
        run: |
          mkdir -p ./.vitepress/dist/lark-docs
          cp -r ./dist-lark/* ./.vitepress/dist/lark-docs/
      - name: Build with rspress
        run: pnpm build:rspress
      - name: Merge rspress site into /h/rspress/
        run: |
          mkdir -p ./.vitepress/dist/rspress
          cp -r ./dist-rspress/* ./.vitepress/dist/rspress/
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./.vitepress/dist
  deploy:
    if: "${{ github.event_name == 'workflow_dispatch' }}"
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    needs: build
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
